### ISSUE TITLE
Search in Classifieds is too bad to be used as meaningful tests

### ISSUE THREAD

**Issue by mondaychen** [web-arena-x/visualwebarena#11]
For example, when searching for "blue kayak" http://ec2-3-13-232-171.us-east-2.compute.amazonaws.com:9980/index.php?page=search&sOrder=dt_pub_date&iOrderType=desc&sPattern=blue+kayak

The result shows nothing related to kayak at all (and none of them are red)
![image](https://github.com/web-arena-x/visualwebarena/assets/1001890/5a47b7a6-2bcb-4018-9559-24817670a40f)

**Comment by kohjingyu** [comment]
Thanks for bringing this up! We're aware that the search is not great, unfortunately this is a [limitation of the OSClass backend](https://forums.osclasspoint.com/stela-osclass-theme/search-results-problem/), so this might also be representative of several real world classifieds sites. We tried various search strategies but none of them were super great, but we structured all the tasks to minimize ambiguity (e.g., the blue kayak task can instead be solved by looking in the boats category, which is more principled as "blue" is not always in the text anyway). Other tasks (e.g., [34](https://github.com/web-arena-x/visualwebarena/blob/main/config_files/test_classifieds.raw.json#L1333)) explicitly tell the agent what to search to hopefully minimize these types of situations.
