### ISSUE TITLE
What are the multi-site tasks mentioned in the paper?

### ISSUE THREAD

**Issue by XinrunXu** [web-arena-x/visualwebarena#14]
<img width="630" alt="image" src="https://github.com/web-arena-x/visualwebarena/assets/152240558/36118f90-27fd-49f8-992f-b72c71a0bb2d">

Where can I find them directly?

**Comment by kohjingyu** [comment]
You can filter by all the tasks in `config_files/test_classifieds.raw.json`, `config_files/test_shopping.raw.json` and `config_files/test_reddit.raw.json` in that have multiple sites in `"sites"`, e.g., task 43 of `test_reddit.raw.json`:

https://github.com/web-arena-x/visualwebarena/blob/0675e395c78f7491071c08681153950f3931abce/config_files/test_reddit.raw.json#L1477-L1480

**Comment by XinrunXu** [comment]
Thank you!
