### ISSUE TITLE
Questions about pytest -x

### ISSUE THREAD

**Issue by XinrunXu** [web-arena-x/visualwebarena#16]
Performed the following installation operations as required
![image](https://github.com/web-arena-x/visualwebarena/assets/152240558/50323064-59a0-4144-b74a-9a0bdf00b34e)

but
![image](https://github.com/web-arena-x/visualwebarena/assets/152240558/71c9b009-40e2-47de-86e3-7f1bfa8416da)

**Comment by kohjingyu** [comment]
Hi, this is because you need the [URLs to be set](https://github.com/web-arena-x/visualwebarena/?tab=readme-ov-file#end-to-end-evaluation) before running pytest (as it needs access to these webpages for some of the tests).

**Comment by XinrunXu** [comment]
I ran all the environment installation commands, but I don't have the _state.json file in .auth folder.

**Comment by XinrunXu** [comment]
python browser_env/auto_login.py
After running the above command, the _state.json file was not created.
