### ISSUE TITLE
Trouble with Checkboxes

### ISSUE THREAD

**Issue by gurugecl** [web-arena-x/visualwebarena#18]
Hi, I tried your demo agent on my web application and for most interactions it does well. However it seems to have trouble with identifying/clicking on checkboxes. Is there some way to perhaps improve or resolve that?

<img width="160" alt="Screenshot 2024-04-03 at 2 59 36 pm" src="https://github.com/web-arena-x/visualwebarena/assets/14853874/60d46cec-e34d-49c8-ad3e-ca651fe2a8e2">

**Comment by kohjingyu** [comment]
Thanks, this is a great suggestion! Can you provide a link to an example webpage? Is it the standard `input type="checkbox"` element?

**Comment by gurugecl** [comment]
Yes it uses input type="checkbox". Unfortunately this is from an internal application but I below is the code for a similar sample html page form that mimics the setup so if it can make selections from this then I believe it should work for other similar applications

`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Custom Form with Checkboxes and Dropdowns</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }
        .section {
            margin-bottom: 20px;
        }
        .section h3 {
            font-size: 18px;
            margin-bottom: 10px;
        }
        .checkbox-row {
            display: flex;
            flex-wrap: wrap;
            gap: 15px;
        }
        .checkbox-row label {
    display: flex;
    align-items: center;
    gap: 10px; 
    padding: 10px;
    cursor: pointer;
}

.checkbox-row input[type="checkbox"] {
    transform: scale(1.5);
    margin-right: 10px;
    cursor: pointer;
}
.checkbox-group {
    display: grid;
    grid-template-columns: repeat(3, 1fr); 
    gap: 15px;
    align-items: center;
}

        .dropdown-group {
            margin-top: 10px;
        }
        .dropdown-group select {
            width: 200px;
            padding: 10px;
            margin-top: 5px;
        }
        button {
            padding: 10px 20px;
            background-color: #5c87b2;
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 16px;
        }
        button:hover {
            background-color: #3c5f82;
        }
    </style>
</head>
<body>
    <h1>Custom Search Form</h1>
    <form id="searchForm">
        
        <div class="section">
            <h3>Select months of the year:</h3>
            <div class="checkbox-row">
                <input type="checkbox" id="january" name="months" value="January">
                <label for="january">January</label>
                <input type="checkbox" id="february" name="months" value="February">
                <label for="february">February</label>
                <input type="checkbox" id="march" name="months" value="March">
                <label for="march">March</label>
            </div>
        </div>
        
        
        <div class="section">
            <h3>Select planets:</h3>
            <div class="checkbox-row">
                <input type="checkbox" id="mercury" name="planets" value="Mercury">
                <label for="mercury">Mercury</label>
                <input type="checkbox" id="venus" name="planets" value="Venus">
                <label for="venus">Venus</label>
                <input type="checkbox" id="earth" name="planets" value="Earth">
                <label for="earth">Earth</label>
            </div>
            <div class="checkbox-row">
                <input type="checkbox" id="mars" name="planets" value="Mars">
                <label for="mars">Mars</label>
                <input type="checkbox" id="jupiter" name="planets" value="Jupiter">
                <label for="jupiter">Jupiter</label>
                <input type="checkbox" id="saturn" name="planets" value="Saturn">
                <label for="saturn">Saturn</label>
            </div>
        </div>
        
        
        <div class="section">
            <h3>Select animals:</h3>
            <div class="checkbox-row">
                <input type="checkbox" id="lion" name="animals" value="Lion">
                <label for="lion">Lion</label>
                <input type="checkbox" id="tiger" name="animals" value="Tiger">
                <label for="tiger">Tiger</label>
                <input type="checkbox" id="bear" name="animals" value="Bear">
                <label for="bear">Bear</label>
            </div>
            <div class="checkbox-row">
                <input type="checkbox" id="wolf" name="animals" value="Wolf">
                <label for="wolf">Wolf</label>
                <input type="checkbox" id="fox" name="animals" value="Fox">
                <label for="fox">Fox</label>
                <input type="checkbox" id="eagle" name="animals" value="Eagle">
                <label for="eagle">Eagle</label>
            </div>
            <div class="checkbox-row">
                <input type="checkbox" id="shark" name="animals" value="Shark">
                <label for="shark">Shark</label>
                <input type="checkbox" id="dolphin" name="animals" value="Dolphin">
                <label for="dolphin">Dolphin</label>
                <input type="checkbox" id="whale" name="animals" value="Whale">
                <label for="whale">Whale</label>
            </div>
        </div>
        
        
        <div class="dropdown-group">
            <label for="mythical_creature">Choose a mythical creature:</label>
            <select id="mythical_creature" name="mythical_creature">
                <option value="">Select one...</option>
                <option value="Dragon">Dragon</option>
                <option value="Phoenix">Phoenix</option>
                <option value="Unicorn">Unicorn</option>
            </select>
        </div>
        
        
        <div class="dropdown-group">
            <label for="ancient_artifact">Choose an ancient artifact:</label>
            <select id="ancient_artifact" name="ancient_artifact">
                <option value="">Select one...</option>
                <option value="Excalibur">Excalibur</option>
                <option value="Holy Grail">Holy Grail</option>
            </select>
        </div>
        
        <button type="submit">Submit</button>
    </form>

    <div id="result"></div>

    <script>
        document.getElementById('searchForm').addEventListener('submit', function(event) {
            event.preventDefault();
            var formData = new FormData(event.target);
            var resultsDiv = document.getElementById('result');
            resultsDiv.innerHTML = '<h2>Selected Options:</h2>';

            formData.forEach(function(value, key) {
                var name = key.charAt(0).toUpperCase() + key.slice(1);
                resultsDiv.innerHTML += `<p>${name}: ${value}</p>`;
            });
        });
    </script>
</body>
</html>
`

**Comment by kohjingyu** [comment]
Sorry for the delay on this! Thanks to @ljang0, we now have it working for checkboxes: https://github.com/web-arena-x/visualwebarena/commit/f8a6e28f51afbb77708a7ce4f4da3440225d3ee0

Let us know if you run into any issues!

**Comment by gurugecl** [comment]
Great, thanks a lot for working on that! So it does work on the example html form I shared above. However when I try it on our actual application it still seems unable to select checkboxes even though all other elements work (eg buttons, dropdowns etc). Just fyi this is a django app in case that makes any difference. It keeps saying that there are no IDs for the checkbox

Example agent message:
"In summary, the next action I will perform is ```click [checkbox_id]```, but the current screenshot does not show any interactable elements with IDs next to the checkboxes, so I'm unable to proceed with a click action for transcriptomics. 
In such cases where elements that need interaction are not labeled with an ID, it is customary to attempt a scroll action in the hopes of updating the page view to reveal the necessary element IDs"

Here is a basic example of the actual html page but please let me know if anything else would be helpful to see

```
{% extends "base_layout.html" %}
{% block content %}
<section id="main">
<div class="inner">
<h1>Filter</h1>
<form action="{%url 'platform-filtered-index-list'%}" method="get">
<h2>Sources Filtering</h2>
Specifies targets must be avaialable...<br><br> 
	<h3>Select the sources to filter on:</h3>
	By defualt the filters are applied to both ..... sources.<br><br>
	<input type="checkbox" id="fo_source" value="fo_source" name="fo_sourcetype" checked/>
	<label for="fo_source">Observed Data</label>
	<input type="checkbox" id="external_source" value="external_source" name="ext_sourcetype" checked/>
	<label for="external_source">Other Data</label> 
	<h3>Select from among the following data types to include in the search:</h3>
	Only data sources matching these types will be included in the index.<br><br>
	<div class="row uniform 50%">
	{%for dts in datatype_choices %}	
		<div class="4u 12u$(xsmall)">
			<input type="checkbox" id="{{dts}}" value="{{dts}}" name="datatype_selection">
			<label for="{{dts}}">{{dts}}</label>
		</div>
	{% endfor %}
	</div>
<br>
	<section>
	<h3>Select from among the following data types to include in the search:</h3>
	Only data sources marked with these types will be included.<br><br>
	<div class="row uniform 50%">
	{%for tts in tissue_choices %}	
		<div class="4u 12u$(xsmall)">
			<input type="checkbox" id="{{tts}}" value="{{tts}}" name="tissue_selection">
			<label for="{{tts}}">{{tts}}</label>
		</div>
	{% endfor %}
	</div>
	</section>
	{%comment%}
<br>
	<h3>Select from among the following methods to require in the search:</h3> 
	<div class="row uniform 50%">
	{%for pts in analysis_choices %}	
		<div class="4u 12u$(xsmall)">
			<input type="checkbox" id="{{pts.0}}" value="{{pts.0}}" name="analysis_selection">
			<label for="{{pts.0}}">{{pts.0}}</label>
		</div>
	{% endfor %}
	</div>
<br>
	<h3>Choose how to filter on external data</h3>
	If 'Up' or 'Down' is selected, only entries marked with the chosen direction will be included.<br>
	<select name="ext_selection">
		{%for regs in ext_choices%}	
		<option value='{{regs}}'>{{regs}}</option>
		{%endfor%}
	</select>
	<p>
	<h3>Data Type</h3>
	You may filter by AND/OR clauses<br>
	AND checkbox displays targets only if all the checked requirements below are true. The OR checkbox returns targets if any of the checked conditions below are true<br><br>
	<input type="checkbox" id="and_checkbox" value="and_checkbox" name="and_clause" checked/>
	<label for="and_checkbox">AND</label>
	<input type="checkbox" id="or_checkbox" value="or_checkbox" name="or_clause"/>
	<label for="or_checkbox">OR</label>
	<br>
<p>
<br>
<br>
<input style="border-radius: 10px;" type="submit" value="Generate Index">
</form>
</div>
</section>
{% endblock %}


```
