### ISSUE TITLE
Blank screenshot when running GPT-4V + SOM

### ISSUE THREAD

**Issue by ltzheng** [web-arena-x/visualwebarena#19]
The screenshot seems problematic when I run the GPT-4V + SoM agent with the following flags:
```bash
python run.py \
  --instruction_path agent/prompts/jsons/p_som_cot_id_actree_3s.json \
  --test_start_idx 0 \
  --test_end_idx 1 \
  --result_dir <your_result_dir> \
  --test_config_base_dir=config_files/test_shopping \
  --model gpt-4-vision-preview \
  --action_set_tag som  --observation_type image_som
```
Here is part of the render_0.html:
<img width="1919" alt="image" src="https://github.com/web-arena-x/visualwebarena/assets/44831678/b13f91cd-466a-4e9b-a85b-a55685eb45bd">
The GPT response also shows that the image sent was empty.

**Comment by kohjingyu** [comment]
Did you set the appropriate ENV variables and run `scripts/generate_test_data.py` (see [instructions](https://github.com/kohjingyu/vwa_search/commit/502308667282575d49a140b6ba54615e0819da14))? I'd double check what the 0.json config file looks like, and whether you can open the URL from your own web browser.

**Comment by ltzheng** [comment]
Thanks. It is probably due to running on a headless machine. I switch to a machine with a display and it works fine.
