### ISSUE TITLE
Configurations Setup for all Model Types

### ISSUE THREAD

**Issue by anithselva** [web-arena-x/visualwebarena#30]
Hello,

Could you please share some of the configuration settings to reproduce the various model types? 

I tried to reproduce the caption-augmented setup (Acc Tre + Caps) but my value was closer to the Multimodal result that had the Image Screenshot also as an input. Hoping I could get more clarification on how to switch between the 4 modes. 

Here is my configurations

(1) Text-Only
observation_type: accessibility_tree
action_set_tag: id_accessibility_tree

(2) Caption-Augmented
observation_type: accessibility_tree_with_captioner
action_set_tag: id_accessibility_tree

(3) Multimodal
observation_type: ???
action_set_tag: id_accessibility_tree

(4) Multimodal (SoM)
observation_type: image_som
action_set_tag: som

**Comment by kohjingyu** [comment]
For the multimodal setting you should be running it with 
```
observation_type: accessibility_tree_with_captioner
action_set_tag: id_accessibility_tree
```

but using a [multimodal LM](https://github.com/web-arena-x/visualwebarena/blob/b6c9b643c430ea6fdc253e1cc02aa66223d4c57f/agent/agent.py#L119), which will automatically use the screenshot as additional input alongside the accessibility tree. If you use a text-only LM then it will not provide the screenshot. Hope that helps!

**Comment by anithselva** [comment]
@kohjingyu That's helpful! But then how do I run the Caption Augmented mode, using Gemini-Pro as the LLM backbone (and BLIP as Visual Backbone)?

I noticed there is an instruction config where the prompt type is specified as a MultimodalCOTPrompt. Will switching to that config do the trick?

i.e. 

(2) Caption-Augmented
instruction_path: p_multimodal_cot_id_actree_3s
observation_type: accessibility_tree_with_captioner
action_set_tag: id_accessibility_tree

(3) Multimodal
instruction_path: p_som_cot_id_actree_3s
observation_type: ?accessibility_tree_with_captioner
action_set_tag: id_accessibility_tree

Is that correct?

**Comment by anithselva** [comment]
That makes sense - I had mis-pasted my configurations in my summary, so sorry if my example and my text writeup was not consistent. 

Thanks for rectifying and confirming that instruction path would help switch the modes!

Appreciate the fast response.

**Comment by anithselva** [comment]
Hello @kohjingyu ,

I'm having issues with running the Gemini model. Using the p_cot_id_actree_3s path, I ran into the error that the google provider is not implemened.

Looking at the PromptConstructor in the `get_lm_api_input` function, I only see support for the openai provider.

Do you have a git branch or code commit that supported the Gemini LM to produce the results in Table 3?

**Comment by kohjingyu** [comment]
The google provider should be implemented, see the [llms/utils.py](https://github.com/web-arena-x/visualwebarena/blob/main/llms/utils.py#L61) file. If you can isolate where the error is being thrown that'd probably provide some hint for debugging

**Comment by anithselva** [comment]
@kohjingyu 

Here is how I run the test:

```

model="gemini"
result_dir="classifieds_gemini_caption_augmented_test"
instruction_path="agent/prompts/jsons/p_cot_id_actree_3s.json"
captioning_model="Salesforce/blip2-flan-t5-xl"

# Define the batch size variable
batch_size=50

# Define the starting and ending indices
start_idx=0
end_idx=$((start_idx + batch_size))
max_idx=233

# Loop until the starting index is less than or equal to 466
while [ $start_idx -le $max_idx ]
do
    # Classifieds reset is quick, so we can do it after every example.
    curl -X POST http:/localhost:9980/index.php?page=reset -d "token=4b61655535e7ed388f0d40a93600254c"
    bash prepare.sh
    python run.py \
     --instruction_path $instruction_path \
     --test_start_idx $start_idx \
     --test_end_idx $end_idx \
     --model $model \
     --result_dir $result_dir \
     --test_config_base_dir=config_files/test_classifieds \
     --repeating_action_failure_th 5 --viewport_height 2048 \
     --captioning_model $captioning_model \
     --provider google --mode completion --max_obs_length 15360 \
     --observation_type accessibility_tree_with_captioner

```
and here is a copy of the output log including the error:

```
(vwa) 
Done convert python files to json
Total 45 tasks left
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████| 2/2 [01:10<00:00, 35.13s/it]
2024-05-07 14:46:14,732 - INFO - [Config file]: config_files/test_classifieds/5.json
2024-05-07 14:46:14,732 - INFO - [Intent]: Navigate to my listing of the white car and delete it.
Reset Classifieds site.
NOTE: This is a Gemini model, so we use characters instead of tokens for max_obs_length.
2024-05-07 14:47:10,508 - INFO - [Unhandled Error] NotImplementedError('Provider google not implemented TP3')]
2024-05-07 14:47:10,510 - INFO - [Config file]: config_files/test_classifieds/6.json
2024-05-07 14:47:10,510 - INFO - [Intent]: Return the links of the 3 most recent motorcycles within $1000 to $2000 that are not orange.

```

I traced the error back to this function https://github.com/web-arena-x/visualwebarena/blob/main/agent/prompts/prompt_constructor.py#L39-L113
In that, HF and OpenAI providers are supported but not google

I believe this is because in the text-only setup, the instruction config `p_cot_id_actree_3s` uses the `CoTPromptConstructor` instead of the `MultimodalCoTPromptConstructor`. In that, the inherited `get_llm_input` function from `PromptConstructor`, doesn't support the google provider.

I was able to make the appropriate modifications to get the code run, but it would be preferable to get the exact code that was used to produce the numbers from the paper, since I'm seeing a large gap between the reported number and what I measured:

Classifieds
Caption Augmented - Google Gemini, BLIP Vision Encoder
Measured: 6.01
Reported: 1.71

**Comment by kohjingyu** [comment]
Are you running this on the full subset (all 910 tasks)?

**Comment by anithselva** [comment]
@kohjingyu -
I'm testing on the full 253 classified tasks from the config https://github.com/web-arena-x/visualwebarena/blob/main/config_files/test_classifieds.raw.json

I haven't run it on the reddit or shopping tasks. Wanted to close the gap on the classifieds first.

**Comment by kohjingyu** [comment]
Is this Gemini Pro 1.0 or 1.5? The result from the paper is from the preview version of Gemini, and both the 1.0 and 1.5 release versions get different results (1.0 seems worse than the paper, but 1.5 is much better)

**Comment by anithselva** [comment]
I've tried both 1.0 and 1.5. In both cases the numbers for caption
augmented were significantly higher than reported in the paper, which made
me concerned that my configuration was incorrect.

Good to know that the results were obtained from preview version of Gemini.
I look forward to the results on 1.5. Do you have an approx timeline?

**Comment by kohjingyu** [comment]
Forgot to update this, but the results are in the paper now!
