### ISSUE TITLE
Could you please release the code about how to run the CogVLM?

### ISSUE THREAD

**Issue by leoozy** [web-arena-x/visualwebarena#33]
In the paper, you said you truncate the input text to 640 tokens for cogvlm. But it may dicard the important choices. Could you plz share how you construct the prompt for CogVLM?

**Comment by kohjingyu** [comment]
We truncate the accessibility tree to keep the first 640 tokens. Yes you lose some information but there isn't really a good solution to this since its context length is so limited.
