### ISSUE TITLE
How do you evaluate CogVLM when there are multiple images as input.

### ISSUE THREAD

**Issue by leoozy** [web-arena-x/visualwebarena#36]
CogVLM only supports a single image as input. How do you evaluate CogVLM when there are multiple images as input. Thank you.

**Comment by kohjingyu** [comment]
CogVLM wasn't trained with multiple images but it can technically handle multiple images as input (see https://github.com/THUDM/CogVLM/issues/93). This is not ideal but maybe better than removing some of the few shot prompts. I don't think it's a good baseline for VWA for this reason and for the short context length.
