### ISSUE TITLE
Evaluation always skips last task for any website

### ISSUE THREAD

**Issue by vardaan123** [web-arena-x/visualwebarena#39]
The evaluation script  https://github.com/web-arena-x/visualwebarena/blob/main/scripts/run_reddit_som.sh goes till index 208 and not till 209 as it should for 210 total examples. Similarly, https://github.com/web-arena-x/visualwebarena/blob/main/scripts/run_classifieds_som.sh goes till 232 and not 233 as it should for 234 examples. It is an easy fix, just want to confirm.

**Comment by kohjingyu** [comment]
Thanks for flagging this, and you're right. It's been fixed with https://github.com/web-arena-x/visualwebarena/commit/85fcbe088ca8218295a36fd5c1d6b1716920a6f1.
