### ISSUE TITLE
Archive.org Download Links Not Working

### ISSUE THREAD

**Issue by jdy18** [web-arena-x/visualwebarena#42]
Hello,

I hope this message finds you well. I encountered an issue with the download links for the WebArena environment images hosted on Archive.org. The links appear to be broken and display an error message regarding metadata issues.

Affected Links:

[Shopping Website Image](https://archive.org/download/webarena-env-shopping-image)
[Wikipedia Website Image](https://archive.org/download/webarena-env-wiki-image)
Could you please look into this and provide updated links or fix the current ones?

Thank you very much for your assistance!

![image](https://github.com/web-arena-x/visualwebarena/assets/52999149/d4963073-277f-48a5-8903-e2386d0751e2)

**Comment by kohjingyu** [comment]
Archive seems to have taken down the WebArena images, I'd suggest that you use the Google Drive or CMU mirrors to download them. We'll try to reupload them soon but the files are large and will take a while.
