### ISSUE TITLE
AssertionError: Cookie ./.auth/reddit_state.json expired.

### ISSUE THREAD

**Issue by leoozy** [web-arena-x/visualwebarena#49]
Thank you for your work. I reset the reddit by 
`bash ./scripts/reset_redddit.sh`
 Then run the prepare.sh, but alway meet the following error:
```
Traceback (most recent call last):
  File "code/vwa/browser_env/auto_login.py", line 182, in <module>
    main()
  File "code/vwa/browser_env/auto_login.py", line 173, in main
    assert not future.result(), f"Cookie {cookie_files[i]} expired."
AssertionError: Cookie ./.auth/reddit_state.json expired.

```

**Comment by shuyanzhou** [comment]
Thanks for reporting this! Seems like this is not a common issue. Can you double-check if the URLs are identical in `task_id.json` and `env_config.json`?

Another way to debug is to log in with the browser to see if the website functions correctly. You can also try to launch `auto_login.py` with `headless=False` [here](https://github.com/web-arena-x/visualwebarena/blob/main/browser_env/auto_login.py#L48) and pass `--site_list reddit` to see what is actually going on

**Comment by leoozy** [comment]
Thanks！
