### ISSUE TITLE
action space of som can not solve the select element

### ISSUE THREAD

**Issue by leoozy** [web-arena-x/visualwebarena#54]
<img width="410" alt="image" src="https://github.com/web-arena-x/visualwebarena/assets/26025961/6b08997b-1d57-4d72-a424-c0ef7637d84e">
There is no index in the selections

**Comment by leoozy** [comment]
There is no idx for selections in 27

**Comment by kohjingyu** [comment]
This is a known issue with the current SoM markup, we're not sure there's a good way to fix it. It's possible for the model to select those things by typing into SELECT instead (or using the arrow keys).

**Comment by boyugou** [comment]
SELECT seemingly is not in current Action space. Is there any specific reason for this design? Sometimes Select Option is almost impossible to be finished by CLICK.
