### ISSUE TITLE
Release log of success/failures for GPT4+SOM trajectories

### ISSUE THREAD

**Issue by sanjari-orb** [web-arena-x/visualwebarena#58]
Thanks to the authors for releasing the [GPT4+SOM trajectories](https://drive.google.com/file/d/1-tKz5ByWa1-jwtejiFgxli8fZcBPZgAE/view).

However, I do not see any way to find which traces correspond to succeeding tasks v/s failing tasks. Can this information be released as well? 

This was done in the WebArena repository while releasing the GPT execution traces: https://github.com/web-arena-x/webarena/tree/main/resources#1132023-execution-traces-from-our-experiments-v2

**Comment by kohjingyu** [comment]
This should be available in the zip file you linked, as `classifieds_gpt4v_som/results.txt`, `reddit_gpt4v_som/results.txt`, and `shopping_gpt4v_som/results.txt`:

<img width="721" alt="Screenshot 2024-07-22 at 7 55 43 PM" src="https://github.com/user-attachments/assets/ff101539-d8b9-4742-89f0-dceea84e593b">

**Comment by sanjari-orb** [comment]
I missed this, thanks!
