### ISSUE TITLE
about  CogVLM 

### ISSUE THREAD

**Issue by jun0wanan** [web-arena-x/visualwebarena#7]
hi,

When there are many images on a webpage, how do you handle the input length limit of CogVLM?

Thanks!

**Comment by kohjingyu** [comment]
Hi, we basically truncate the text input to be shorter to fit into the input length limit for the models with shorter context lengths:

<img width="824" alt="Screenshot 2024-02-19 at 5 36 08 PM" src="https://github.com/web-arena-x/visualwebarena/assets/2196979/ae313948-5648-465a-9efc-191456b2876f">

**Comment by jun0wanan** [comment]
> Hi, we basically truncate the text input to be shorter to fit into the input length limit for the models with shorter context lengths:
> 
> <img alt="Screenshot 2024-02-19 at 5 36 08 PM" width="824" src="https://private-user-images.githubusercontent.com/2196979/306086853-ae313948-5648-465a-9efc-191456b2876f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MTcyMTUsIm5iZiI6MTcwODQxNjkxNSwicGF0aCI6Ii8yMTk2OTc5LzMwNjA4Njg1My1hZTMxMzk0OC01NjQ4LTQ2NWEtOWVmYy0xOTE0NTZiMjg3NmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjBUMDgxNTE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTBmMDdmMWVkNWFkZjk5NjY0ZTYyNzU4MDhhMDA4NjE3NGQ2MzFlNDA1NDlhZjc4YmYxZmM3ZTMwNmVlMGY0NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.HhcxVURGt-PLqRvLEuv0C9fyf8Jz_-YyqlGr47sXHr8">
> This can be set with the `--max_obs_length` command line argument:
> 
> https://github.com/web-arena-x/visualwebarena/blob/edc152e4a3fa4fa7e7007ef7d5a80e2927f26e0e/run.py#L162-L167

Hello, I would like to ask if the Gemini-pro-vision does not accept multi-turn dialogue, so are you testing single-turn dialogue with Gemini?

**Comment by jun0wanan** [comment]
> Hi, we basically truncate the text input to be shorter to fit into the input length limit for the models with shorter context lengths

And, 
If truncation is performed, indeed, it will lead to incomplete content, which might affect the final outcome？🤔

**Comment by jun0wanan** [comment]
> Hi, we basically truncate the text input to be shorter to fit into the input length limit for the models with shorter context lengths:
> 
> <img alt="Screenshot 2024-02-19 at 5 36 08 PM" width="824" src="https://private-user-images.githubusercontent.com/2196979/306086853-ae313948-5648-465a-9efc-191456b2876f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0Mzk4MTcsIm5iZiI6MTcwODQzOTUxNywicGF0aCI6Ii8yMTk2OTc5LzMwNjA4Njg1My1hZTMxMzk0OC01NjQ4LTQ2NWEtOWVmYy0xOTE0NTZiMjg3NmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjBUMTQzMTU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzVkMDI1MzhlNDU1ZjY2N2UxYmRmNjYwY2RhYzU3MTJmZWI0ZjkwMGM4YTc1Mzc4ODQwMzI4OGY3NGRlYWViMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6w_OVsA1A1V4HNjutOpbsWQxHQ2LQaErKd5Llck7s7U">
> This can be set with the `--max_obs_length` command line argument:
> 
> https://github.com/web-arena-x/visualwebarena/blob/edc152e4a3fa4fa7e7007ef7d5a80e2927f26e0e/run.py#L162-L167

I also find if I choose the website have more text-image , it will get the bug using gemini-pro-vision:

 HTTPSConnectionPool(host='generativelanguage.googleapis.com', port=443): Read timed out. (read timeout=60.0)
 
 How can you solve it ? Thank you!

**Comment by kohjingyu** [comment]
> So, gemini-pro-vision only input text-image format information?

You can find our prompt for Gemini here: https://github.com/web-arena-x/visualwebarena/blob/edc152e4a3fa4fa7e7007ef7d5a80e2927f26e0e/agent/prompts/prompt_constructor.py#L396-L430


> If truncation is performed, indeed, it will lead to incomplete content, which might affect the final outcome？🤔

Yes, we've noticed that longer context models (e.g., gpt-3.5-turbo-16k instead of gpt-3.5-turbo-4k) are generally better at web tasks. There's not much you can do when the model has a limited max context length though.

> I also find if I choose the website have more text-image , it will get the bug using gemini-pro-vision:
> 
> HTTPSConnectionPool(host='generativelanguage.googleapis.com', port=443): Read timed out. (read timeout=60.0)
> 
> How can you solve it ? Thank you!

As long as the max input length is shorter than what Gemini can handle ([12288 tokens for gemini-pro-vision](https://ai.google.dev/models/gemini)), it shouldn't fail here. I'd probably try increasing the timeout or opening an issue with Google if the token count is below 12288 and it persists.

**Comment by jun0wanan** [comment]
> > So, gemini-pro-vision only input text-image format information?
> 
> You can find our prompt for Gemini here:
> 
> https://github.com/web-arena-x/visualwebarena/blob/edc152e4a3fa4fa7e7007ef7d5a80e2927f26e0e/agent/prompts/prompt_constructor.py#L396-L430
> 
> > If truncation is performed, indeed, it will lead to incomplete content, which might affect the final outcome？🤔
> 
> Yes, we've noticed that longer context models (e.g., gpt-3.5-turbo-16k instead of gpt-3.5-turbo-4k) are generally better at web tasks. There's not much you can do when the model has a limited max context length though.
> 
> > I also find if I choose the website have more text-image , it will get the bug using gemini-pro-vision:
> > HTTPSConnectionPool(host='generativelanguage.googleapis.com', port=443): Read timed out. (read timeout=60.0)
> > How can you solve it ? Thank you!
> 
> As long as the max input length is shorter than what Gemini can handle ([12288 tokens for gemini-pro-vision](https://ai.google.dev/models/gemini)), it shouldn't fail here. I'd probably try increasing the timeout or opening an issue with Google if the token count is below 12288 and it persists.

Thank you!
