### ISSUE TITLE
docker compose takes too much time, always fails here. 

### ISSUE THREAD

**Issue by youbaowangsheng** [web-arena-x/visualwebarena#8]
docker compose up --build -d
# Wait for compose up to finish. This may take a while on the first launch as it downloads several large images from dockerhub.

Can we just download with SFTP or other tools instead?

**Comment by kohjingyu** [comment]
Hi, what's the actual error when it fails? We've only gotten an error if the local disk does not have enough space for the environments, which can be quite large (77.4GB for the final Classifieds docker image, and more during setup). Can you check if you have sufficient storage?

**Comment by youbaowangsheng** [comment]
![WechatIMG250](https://github.com/web-arena-x/visualwebarena/assets/48280583/3720fffd-8b68-4395-bf45-14c52e19517b)
EOFError, seems network error.

**Comment by youbaowangsheng** [comment]
Always like this , can somebody help me out?
![Uploading WechatIMG1893.jpg…]()

**Comment by kohjingyu** [comment]
Unfortunately we cannot reproduce this. Can you run with `docker compose --verbose up` and let us know what the full error looks like?

**Comment by HeoeH** [comment]
I have the same question，how do you solve it？
